FROM    oliverf/fhem:22183

LABEL   maintainer="Oliver Friesen <oliver.friesen@gmail.com>" 

USER	root

# nodejs
RUN	apt-get update && \
	apt-get --quiet --yes --no-install-recommends install \
		curl \
		apt-transport-https \
		ca-certificates \
		gnupg && \
	curl -s http://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
	echo 'deb https://deb.nodesource.com/node_13.x buster main' > /etc/apt/sources.list.d/nodesource.list && \
	echo 'deb-src https://deb.nodesource.com/node_13.x buster main' >> /etc/apt/sources.list.d/nodesource.list && \
	apt-get update && \
	apt-get --quiet --yes --no-install-recommends install \
		nodejs \
                gyp \
                openssh-client && \
        apt-get -q -y clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

# Alexa
RUN     npm install -g --unsafe-perm --production alexa-fhem

USER	fhem
